server:
  port: 7070
spring:
  datasource:
    name: post_item
    url: jdbc:mysql://127.0.0.1/test
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    
